import { AfterViewInit, Component, OnDestroy, computed, inject, signal, viewChild } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import type { ColDef, GetRowIdParams, GridOptions } from 'ag-grid-community';
import { Button } from 'primeng/button';
import { Tag } from 'primeng/tag';
import { SelectButton } from 'primeng/selectbutton';
import { Message } from 'primeng/message';
import { FormsModule } from '@angular/forms';
import { MacroAngularGrid } from '@macro/macro-angular-grid';
import type { ColumnFormatMap } from '@macro/macro-grid-format';
import {
  BlotterFeed,
  MODE_LABELS,
  TRANSPORT_LABELS,
  applyInferredFormats,
  inferColumns,
  type BlotterSource,
  type ColumnMode,
  type FeedState,
  type FeedStatus,
  type GridOps,
} from '@macro/prism-core';
import { DataSourceRepository } from '../../services/data-source-repository.service';
import { ActiveSourceService } from '../../services/active-source.service';

type Row = Record<string, unknown>;

@Component({
  selector: 'app-blotter',
  standalone: true,
  imports: [RouterLink, FormsModule, MacroAngularGrid, Button, Tag, SelectButton, Message],
  templateUrl: './blotter.component.html',
  styleUrl: './blotter.component.css',
})
export class BlotterComponent implements AfterViewInit, OnDestroy {
  private readonly grid = viewChild(MacroAngularGrid);
  private readonly repo = inject(DataSourceRepository);
  private readonly activeSource = inject(ActiveSourceService);
  private readonly route = inject(ActivatedRoute);

  readonly transportLabels = TRANSPORT_LABELS;
  readonly modeLabels = MODE_LABELS;

  readonly source = signal<BlotterSource | null>(null);
  readonly columns = signal<ColDef[]>([]);
  readonly formats = signal<ColumnFormatMap>({});
  readonly columnMode = signal<ColumnMode>('infer');
  readonly showGrid = signal(true);

  /** Mirror of the framework-free feed state into a signal so the template stays reactive. */
  private readonly feedState = signal<FeedState>({ status: 'idle', rowCount: 0, msgsPerSec: 0, error: null });

  readonly columnModeOptions = [
    { label: 'Infer', value: 'infer' as ColumnMode },
    { label: 'Auto (v36)', value: 'auto-gen' as ColumnMode },
  ];

  /** Seed the wrapper's format store only on the infer path; auto-gen formats via the callback. */
  readonly seedFormats = computed<ColumnFormatMap>(() => (this.columnMode() === 'infer' ? this.formats() : {}));

  readonly gridOptions = computed<GridOptions>(() =>
    this.columnMode() === 'auto-gen'
      ? {
          autoGenerateColumnDefs: { objectValues: 'flatten', nullishValues: 'include' },
          processAutoGeneratedColumnDefs: applyInferredFormats(this.formats()),
        }
      : {},
  );

  private feed?: BlotterFeed;
  private feedUnsub?: () => void;

  readonly getRowId = (params: GetRowIdParams): string => {
    const src = this.source();
    const data = params.data as Row;
    if (src?.mode === 'append') return String(data['__id']);
    return String(data[src?.keyField ?? '__id']);
  };

  get status(): FeedStatus {
    return this.feedState().status;
  }
  get rowCount(): number {
    return this.feedState().rowCount;
  }
  get msgsPerSec(): number {
    return this.feedState().msgsPerSec;
  }
  get error(): string | null {
    return this.feedState().error;
  }

  statusSeverity(): 'success' | 'danger' | 'warn' | 'secondary' {
    switch (this.status) {
      case 'live':
        return 'success';
      case 'error':
        return 'danger';
      case 'connecting':
      case 'snapshot-loading':
        return 'warn';
      default:
        return 'secondary';
    }
  }

  ngAfterViewInit(): void {
    const src = this.resolveSource();
    if (!src) return;
    this.source.set(src);
    this.columnMode.set(src.columnMode);
    this.startFeed();
  }

  ngOnDestroy(): void {
    this.feedUnsub?.();
    this.feed?.stop();
  }

  setColumnMode(mode: ColumnMode): void {
    if (mode === this.columnMode()) return;
    this.columnMode.set(mode);
    this.reconnect(); // rebuild the grid with the new column strategy
  }

  reconnect(): void {
    this.feedUnsub?.();
    this.feed?.stop();
    // Recreate the grid component (setInitialRowData is one-shot per grid instance).
    this.showGrid.set(false);
    setTimeout(() => {
      this.showGrid.set(true);
      setTimeout(() => this.startFeed(), 0);
    }, 0);
  }

  disconnect(): void {
    this.feed?.stop();
  }

  private startFeed(): void {
    const src = this.source();
    const grid = this.grid();
    if (!src || !grid) return;
    this.columns.set([]);
    // Adapt the Angular grid's Subjects/method to the framework-free GridOps interface.
    const ops: GridOps = {
      addRows: (rows) => grid.addRows$.next(rows),
      updateRows: (rows) => grid.updateRows$.next(rows),
      deleteRows: (rows) => grid.deleteRows$.next(rows),
      setInitialRowData: (rows) => grid.setInitialRowData(rows),
    };
    this.feed = new BlotterFeed(src, ops, (rec) => this.onFirstRecord(rec));
    this.feedState.set(this.feed.getState());
    this.feedUnsub = this.feed.subscribe(() => this.feedState.set(this.feed!.getState()));
    this.feed.start();
  }

  private onFirstRecord(rec: Row): void {
    const src = this.source();
    const { columns, formats } = inferColumns(rec, src?.keyField);
    this.formats.set(formats);
    if (this.columnMode() === 'infer') this.columns.set(columns);
  }

  private resolveSource(): BlotterSource | null {
    const id = this.route.snapshot.queryParamMap.get('source');
    if (id) {
      const found = this.repo.get(id);
      if (found) return found;
    }
    return this.activeSource.active();
  }
}
