export const themes = {
  "neoQuantum": {
    "light": {
      "background1": "#FFFFFF",
      "background2": "#F6F7F9",
      "background3": "#EDEEF2",
      "background4": "#E1E3E8",
      "background5": "#D0D3D9",
      "background6": "#A9AEB8",
      "brandSecondary": "#D0D3D9",
      "brandSecondaryActive": "#C3C6CE",
      "brandSecondaryHover": "#E1E3E8",
      "brandSecondaryFocused": "#09090B",
      "brandSecondaryText": "#09090B",
      "inputBackground": "#EDEEF2",
      "inputColor": "#09090B",
      "inputPlaceholder": "#71717A",
      "inputDisabled": "#A1A1AA",
      "inputFocused": "#0055FF",
      "inputBorder": "#D0D3D9",
      "textDefault": "#09090B",
      "textHelp": "#52525B",
      "textInactive": "#A1A1AA",
      "brandPrimary": "#0055FF",
      "brandPrimaryActive": "#0044CC",
      "brandPrimaryHover": "#3377FF",
      "brandPrimaryFocused": "#FFFFFF",
      "brandPrimaryText": "#FFFFFF",
      "statusSuccess": "#006B2C",
      "statusWarning": "#A36A00",
      "statusCritical": "#B30029",
      "statusActive": "#0055FF",
      "contentBackground1": "#FFFFFF",
      "contentBackground2": "#F6F7F9",
      "contentBackground3": "#EDEEF2",
      "contentBackground4": "#E1E3E8",
      "contentBackground5": "#D0D3D9",
      "borderNeutral": "#A9AEB8"
    },
    "dark": {
      "background1": "#000000",
      "background2": "#0A0A0C",
      "background3": "#121215",
      "background4": "#1C1C21",
      "background5": "#27272F",
      "background6": "#3F3F4A",
      "brandSecondary": "#27272F",
      "brandSecondaryActive": "#1C1C21",
      "brandSecondaryHover": "#3F3F4A",
      "brandSecondaryFocused": "#FFFFFF",
      "brandSecondaryText": "#FFFFFF",
      "inputBackground": "#121215",
      "inputColor": "#FFFFFF",
      "inputPlaceholder": "#71717A",
      "inputDisabled": "#3F3F4A",
      "inputFocused": "#00E5FF",
      "inputBorder": "#27272F",
      "textDefault": "#FFFFFF",
      "textHelp": "#A1A1AA",
      "textInactive": "#52525B",
      "brandPrimary": "#00E5FF",
      "brandPrimaryActive": "#00B8CC",
      "brandPrimaryHover": "#33EEFF",
      "brandPrimaryFocused": "#000000",
      "brandPrimaryText": "#000000",
      "statusSuccess": "#00FF66",
      "statusWarning": "#FFD600",
      "statusCritical": "#FF0055",
      "statusActive": "#00E5FF",
      "contentBackground1": "#000000",
      "contentBackground2": "#0A0A0C",
      "contentBackground3": "#121215",
      "contentBackground4": "#1C1C21",
      "contentBackground5": "#27272F",
      "borderNeutral": "#3F3F4A"
    }
  },
  "midnightTrader": {
    "light": {
      "backgroundPrimary": "#E3EBF3",
      "background1": "#F0F4F8",
      "background2": "#E3EBF3",
      "background3": "#D6E2ED",
      "background4": "#C9D9E7",
      "background5": "#BCD0E1",
      "background6": "#A3BDCF",
      "brandSecondary": "#BCD0E1",
      "brandSecondaryActive": "#B2C6DB",
      "brandSecondaryHover": "#C6DAEA",
      "brandSecondaryFocused": "#0D1F2D",
      "brandSecondaryText": "#0D1F2D",
      "inputBackground": "#C9D9E7",
      "inputColor": "#0D1F2D",
      "inputPlaceholder": "#2C4A5E",
      "inputDisabled": "#6B8396",
      "inputFocused": "#A3BDCF",
      "inputBorder": "#6B8396",
      "textDefault": "#0D1F2D",
      "textHelp": "#1A3344",
      "textInactive": "#6B8396",
      "brandPrimary": "#00B8D4",
      "brandPrimaryActive": "#00A7C0",
      "brandPrimaryHover": "#1AC5DE",
      "brandPrimaryFocused": "#FFFFFF",
      "brandPrimaryText": "#FFFFFF",
      "statusSuccess": "#00C853",
      "statusWarning": "#FFB300",
      "statusCritical": "#FF3D00",
      "statusActive": "#00B8D4",
      "contentBackground1": "#F0F4F8",
      "contentBackground2": "#E3EBF3",
      "contentBackground3": "#D6E2ED",
      "contentBackground4": "#C9D9E7",
      "contentBackground5": "#BCD0E1",
      "borderNeutral": "#8BA6B8"
    },
    "dark": {
      "backgroundPrimary": "#132F4C",
      "background1": "#0A1929",
      "background2": "#132F4C",
      "background3": "#1A3F5C",
      "background4": "#234E6B",
      "background5": "#2D5D7B",
      "background6": "#3D6F8F",
      "brandSecondary": "#2D5D7B",
      "brandSecondaryActive": "#234E6B",
      "brandSecondaryHover": "#3D6F8F",
      "brandSecondaryFocused": "#FFFFFF",
      "brandSecondaryText": "#FFFFFF",
      "inputBackground": "#234E6B",
      "inputColor": "#FFFFFF",
      "inputPlaceholder": "#B2CDDF",
      "inputDisabled": "#5A7A8F",
      "inputFocused": "#00B8D4",
      "inputBorder": "#5A7A8F",
      "textDefault": "#FFFFFF",
      "textHelp": "#D6E8F5",
      "textInactive": "#7A96A8",
      "brandPrimary": "#00D4FF",
      "brandPrimaryActive": "#00BFE8",
      "brandPrimaryHover": "#33DDFF",
      "brandPrimaryFocused": "#0A1929",
      "brandPrimaryText": "#0A1929",
      "statusSuccess": "#00E676",
      "statusWarning": "#FFD54F",
      "statusCritical": "#FF6E40",
      "statusActive": "#00D4FF",
      "contentBackground1": "#0A1929",
      "contentBackground2": "#132F4C",
      "contentBackground3": "#1A3F5C",
      "contentBackground4": "#234E6B",
      "contentBackground5": "#2D5D7B",
      "borderNeutral": "#5A7A8F"
    }
  }
};

export type ThemeName = keyof typeof themes;
export type ThemeMode = 'light' | 'dark';
export type Theme = typeof themes.neoQuantum.light;

export const themeDisplayNames: Record<ThemeName, string> = {
  neoQuantum: "Neo Quantum",
  midnightTrader: "Midnight Trader"
};
