import type { ColDef, ColGroupDef, ProcessAutoGeneratedColumnDefs } from 'ag-grid-community';
import {
  buildCellStyle,
  buildValueFormatter,
  type ColumnFormatMap,
  type ColumnFormatSpec,
  type FormatKind,
} from '@macro/macro-grid-format';

export interface InferResult {
  columns: ColDef[];
  formats: ColumnFormatMap;
}

/** Numeric kinds get right-aligned numeric columns. */
const NUMERIC_KINDS = new Set<FormatKind>([
  'number',
  'integer',
  'percent',
  'basisPoints',
  'currency',
  'compact',
  'multiplier',
  'fxRate',
  'treasury',
]);

/** Pretty header from a field name: `changePercent` → `Change Percent`, `order_id` → `Order Id`. */
export function titleCase(field: string): string {
  return field
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/[_-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

/**
 * Map one field (name + sample value) to a capital-markets format spec via field-name heuristics.
 * Returns `undefined` for plain-text/categorical columns (no value formatter — the user can still
 * pick a format from the tool panel). `keyField` lets a price column on an FX-keyed source render
 * with pip precision.
 */
export function specForField(name: string, value: unknown, keyField?: string): ColumnFormatSpec | undefined {
  const n = name.toLowerCase();
  const isNum = typeof value === 'number';

  // Dates (by name) — before identifiers so `tradeDate` etc. aren't treated as text.
  if (n.includes('timestamp') || /(^|[^a-z])time([^a-z]|$)/.test(n) || n.endsWith('time')) {
    return { kind: 'date', dateStyle: 'datetime' };
  }
  if (n.includes('date') || n.includes('maturity') || n.includes('expiry') || n.includes('settle')) {
    return { kind: 'date', dateStyle: 'date' };
  }

  // Identifiers / categoricals → plain text (no spec). Match `Id`/`_id` suffixes on the ORIGINAL
  // name so we don't swallow words that merely end in "id" (bid, grid, mid).
  const isIdentifier = name.endsWith('Id') || n === 'id' || n.endsWith('_id');
  const isCategorical =
    /(^|_)(cusip|isin|sedol|symbol|ticker|desk|book|trader|account|side|status|type|venue|broker|state|name|ccy|currency)($|_)/.test(
      n,
    ) || n.endsWith('symbol');
  if (isIdentifier || isCategorical) {
    return undefined;
  }

  if (!isNum) return undefined;

  const fxLike = !!keyField && /(symbol|pair|ccypair|ccy_pair)/i.test(keyField);

  // Numeric heuristics (first match wins).
  if (n.includes('bps') || n.includes('basis') || n.includes('dv01')) {
    return { kind: 'basisPoints', decimals: 1, signDisplay: 'always', colorMode: 'posneg' };
  }
  if (n.includes('spread')) {
    return { kind: 'basisPoints', decimals: 1 };
  }
  if (n.includes('pct') || n.includes('percent')) {
    return { kind: 'percent', decimals: 2, signDisplay: 'always', colorMode: 'posneg' };
  }
  if (n.includes('yield') || n.includes('coupon') || n === 'rate' || n.endsWith('rate')) {
    return { kind: 'percent', decimals: 3 };
  }
  if (n === 'pnl' || n.includes('pnl') || n.includes('p&l') || n === 'pl' || n.includes('realized')) {
    return { kind: 'number', decimals: 2, thousands: true, colorMode: 'posneg' };
  }
  if (/(qty|quantity|size|volume|notional|amount|nominal|face)/.test(n)) {
    return { kind: 'integer', thousands: true };
  }
  if (fxLike && /(bid|ask|mid|rate|price|last|spot)/.test(n)) {
    return { kind: 'fxRate', pipDecimals: 5, jpyConvention: true, symbolField: keyField };
  }
  if (/(bid|ask|mid|price|last|open|high|low|close|nav|strike)/.test(n)) {
    return { kind: 'number', decimals: 4 };
  }
  if (n.includes('change')) {
    return { kind: 'number', decimals: 4, signDisplay: 'always', colorMode: 'posneg' };
  }

  return { kind: 'number', decimals: 2 };
}

/** Build `{columns, formats}` from a single representative record. */
export function inferColumns(sample: Record<string, unknown>, keyField?: string): InferResult {
  return buildFromSample(sample, keyField);
}

/** Like {@link inferColumns} but merges the first N rows so sparse fields are still discovered. */
export function inferColumnsFromRows(rows: Record<string, unknown>[], keyField?: string, maxRows = 20): InferResult {
  return buildFromSample(mergeSample(rows, maxRows), keyField);
}

/**
 * A `processAutoGeneratedColumnDefs` callback for the v36 auto-gen path: decorate AG Grid's
 * generated leaf columns with the inferred CM value formatters / cell styles, so auto-gen columns
 * still get capital-markets formatting (which raw auto-gen would otherwise bypass).
 */
export function applyInferredFormats(formats: ColumnFormatMap): ProcessAutoGeneratedColumnDefs {
  return ({ columnDefs }) => {
    forEachLeaf(columnDefs, (c) => {
      const colId = (c.colId ?? c.field) as string | undefined;
      if (!colId) return;
      const spec = formats[colId];
      if (!spec) return;
      const vf = buildValueFormatter(spec);
      if (vf) c.valueFormatter = vf;
      const cs = buildCellStyle(spec, c.cellStyle);
      if (cs) c.cellStyle = cs;
    });
    return columnDefs;
  };
}

// ── internals ──

function buildFromSample(sample: Record<string, unknown>, keyField?: string): InferResult {
  const columns: ColDef[] = [];
  const formats: ColumnFormatMap = {};
  for (const [field, value] of Object.entries(sample)) {
    const col: ColDef = { field, headerName: titleCase(field) };
    if (field === keyField) col.pinned = 'left';
    const spec = specForField(field, value, keyField);
    if (spec) {
      formats[field] = spec;
      if (NUMERIC_KINDS.has(spec.kind)) col.type = 'numericColumn';
    }
    columns.push(col);
  }
  return { columns, formats };
}

/**
 * Merge the first `maxRows` rows into one representative sample record: first non-null value per
 * field wins, so sparse fields (e.g. `yield` null on futures but set on cash) still infer as
 * numeric. Feed a snapshot batch through this before {@link inferColumns}.
 */
export function mergeSample(rows: Record<string, unknown>[], maxRows = 20): Record<string, unknown> {
  const sample: Record<string, unknown> = {};
  for (const row of rows.slice(0, maxRows)) {
    if (!row || typeof row !== 'object') continue;
    for (const [k, v] of Object.entries(row)) {
      if (!(k in sample) || (sample[k] == null && v != null)) sample[k] = v;
    }
  }
  return sample;
}

function forEachLeaf(defs: (ColDef | ColGroupDef)[], fn: (c: ColDef) => void): void {
  for (const d of defs) {
    const children = (d as ColGroupDef).children;
    if (Array.isArray(children)) {
      forEachLeaf(children, fn);
    } else {
      fn(d as ColDef);
    }
  }
}
