import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { ArrowLeft, RefreshCw, Square } from 'lucide-react';
import type { ColDef, GetRowIdParams, GridOptions } from 'ag-grid-community';
import { MacroReactGrid, type MacroReactGridRef } from '@macro/macro-react-grid';
import type { ColumnFormatMap } from '@macro/macro-grid-format';
import {
  BlotterFeed,
  MODE_LABELS,
  TRANSPORT_LABELS,
  applyInferredFormats,
  inferColumns,
  type ColumnMode,
  type FeedState,
  type GridOps,
} from '@macro/prism-core';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { useDataSourceStore } from '../data-source-context';

type Row = Record<string, unknown>;
const IDLE: FeedState = { status: 'idle', rowCount: 0, msgsPerSec: 0, error: null };

export function Blotter() {
  const store = useDataSourceStore();
  const [params] = useSearchParams();
  const sourceId = params.get('source');
  const source = useMemo(() => (sourceId ? store.get(sourceId) ?? null : null), [store, sourceId]);

  const gridRef = useRef<MacroReactGridRef>(null);
  const feedRef = useRef<BlotterFeed | null>(null);

  const [columnMode, setColumnMode] = useState<ColumnMode>('infer');
  const [columns, setColumns] = useState<ColDef[]>([]);
  const [formats, setFormats] = useState<ColumnFormatMap>({});
  const [rowData, setRowData] = useState<unknown[]>([]);
  const [feedState, setFeedState] = useState<FeedState>(IDLE);
  const [gridKey, setGridKey] = useState(0);

  useEffect(() => {
    if (source) setColumnMode(source.columnMode);
  }, [source]);

  const getRowId = useCallback(
    (p: GetRowIdParams) => {
      const data = p.data as Row;
      if (source?.mode === 'append') return String(data['__id']);
      return String(data[source?.keyField ?? '__id']);
    },
    [source],
  );

  const gridOptions = useMemo<GridOptions>(
    () =>
      columnMode === 'auto-gen'
        ? {
            autoGenerateColumnDefs: { objectValues: 'flatten', nullishValues: 'include' },
            processAutoGeneratedColumnDefs: applyInferredFormats(formats),
          }
        : {},
    [columnMode, formats],
  );

  // Create + start the feed when the source / column mode / remount key changes.
  useEffect(() => {
    const grid = gridRef.current;
    if (!source || !grid) return;
    setColumns([]);
    setRowData([]);
    setFeedState(IDLE);

    const ops: GridOps = {
      addRows: (rows) => grid.addRows$.next(rows),
      updateRows: (rows) => grid.updateRows$.next(rows),
      deleteRows: (rows) => grid.deleteRows$.next(rows),
      // The React grid has no setInitialRowData — seed via the rowData prop state.
      setInitialRowData: (rows) => setRowData(rows),
    };
    const feed = new BlotterFeed(source, ops, (rec) => {
      const inferred = inferColumns(rec, source.keyField);
      setFormats(inferred.formats);
      if (columnMode !== 'auto-gen') setColumns(inferred.columns);
    });
    feedRef.current = feed;
    const off = feed.subscribe(() => setFeedState(feed.getState()));
    setFeedState(feed.getState());
    void feed.start();

    return () => {
      off();
      void feed.stop();
      feedRef.current = null;
    };
  }, [source, columnMode, gridKey]);

  const reconnect = () => setGridKey((k) => k + 1);
  const disconnect = () => void feedRef.current?.stop();
  const switchMode = (mode: ColumnMode) => {
    if (mode === columnMode) return;
    setColumnMode(mode);
    setGridKey((k) => k + 1); // remount the grid with the new column strategy
  };

  if (!source) {
    return (
      <div className="flex flex-col items-center gap-4 pt-16 opacity-80">
        <p>No source selected.</p>
        <Button asChild>
          <a href={`${import.meta.env.BASE_URL}sources`}>Back to catalog</a>
        </Button>
      </div>
    );
  }

  const statusVariant =
    feedState.status === 'live'
      ? 'success'
      : feedState.status === 'error'
        ? 'destructive'
        : feedState.status === 'connecting' || feedState.status === 'snapshot-loading'
          ? 'warning'
          : 'secondary';

  return (
    <div className="flex flex-col h-full gap-3">
      <div className="flex items-center gap-3 flex-wrap">
        <a href={`${import.meta.env.BASE_URL}sources`} aria-label="Back to catalog" className="text-foreground">
          <ArrowLeft className="size-5" />
        </a>
        <div className="flex items-center gap-2">
          <span className="font-bold text-lg">{source.name}</span>
          <Badge variant="secondary">{TRANSPORT_LABELS[source.transport]}</Badge>
          <Badge>{MODE_LABELS[source.mode]}</Badge>
        </div>

        <div className="flex items-center gap-3">
          <Badge variant={statusVariant}>{feedState.status}</Badge>
          <span className="text-sm opacity-70">{feedState.rowCount} rows</span>
          <span className="text-sm opacity-70">{feedState.msgsPerSec} msg/s</span>
        </div>

        <div className="ml-auto flex items-center gap-2 flex-wrap">
          <div className="inline-flex rounded-md border overflow-hidden">
            {(['infer', 'auto-gen'] as ColumnMode[]).map((m) => (
              <button
                key={m}
                onClick={() => switchMode(m)}
                className={`text-sm px-3 py-1.5 ${columnMode === m ? 'bg-primary text-primary-foreground' : 'bg-background'}`}
              >
                {m === 'infer' ? 'Infer' : 'Auto (v36)'}
              </button>
            ))}
          </div>
          <Button variant="ghost" size="sm" onClick={reconnect}>
            <RefreshCw className="size-4" /> Reconnect
          </Button>
          <Button variant="ghost" size="sm" onClick={disconnect}>
            <Square className="size-4" /> Disconnect
          </Button>
        </div>
      </div>

      {feedState.error && (
        <div className="rounded-md border border-destructive bg-destructive/10 text-destructive px-3 py-2 text-sm">
          {feedState.error}
        </div>
      )}

      <div className="flex-1 min-h-0">
        <MacroReactGrid
          key={gridKey}
          ref={gridRef}
          columns={columns}
          rowData={rowData}
          columnFormats={columnMode === 'infer' ? formats : {}}
          gridOptions={gridOptions}
          getRowId={getRowId}
        />
      </div>
    </div>
  );
}
