import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { ChevronDown, Database, Plus, RefreshCw, Square } from 'lucide-react';
import type { ColDef, GetRowIdParams, GridOptions } from 'ag-grid-community';
import { MacroReactGrid, type MacroReactGridRef } from '@macro/macro-react-grid';
import type { ColumnFormatMap } from '@macro/macro-grid-format';
import {
  BlotterFeed,
  MODE_LABELS,
  TRANSPORT_LABELS,
  applyInferredFormats,
  inferColumns,
  type BlotterMode,
  type BlotterSource,
  type ColumnMode,
  type FeedState,
  type GridOps,
} from '@macro/prism-core';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { useAllSources, useDataSourceStore } from '../data-source-context';
import { SourcePicker } from './source-picker';
import { AdHocSourceDialog } from './adhoc-source-dialog';

type Row = Record<string, unknown>;
const IDLE: FeedState = { status: 'idle', rowCount: 0, msgsPerSec: 0, error: null };

const modeVariant = (m: BlotterMode): 'success' | 'warning' | 'destructive' =>
  m === 'streaming' ? 'destructive' : m === 'append' ? 'warning' : 'success';

export function Blotter() {
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const sourceId = params.get('source');
  // Reactive over the store so the blotter follows ad-hoc edits/deletes and the async catalog load.
  const all = useAllSources();
  const source = useMemo(
    () => (sourceId ? all.find((s) => s.id === sourceId) ?? null : null),
    [all, sourceId],
  );

  const gridRef = useRef<MacroReactGridRef>(null);
  const feedRef = useRef<BlotterFeed | null>(null);

  const [columnMode, setColumnMode] = useState<ColumnMode>('infer');
  const [modeSourceId, setModeSourceId] = useState<string | null>(null);
  const [columns, setColumns] = useState<ColDef[]>([]);
  const [formats, setFormats] = useState<ColumnFormatMap>({});
  const [rowData, setRowData] = useState<unknown[]>([]);
  const [feedState, setFeedState] = useState<FeedState>(IDLE);
  const [reconnectNonce, setReconnectNonce] = useState(0);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editSource, setEditSource] = useState<BlotterSource | null>(null);

  // When SWITCHING to a different source, adopt its default column mode. Done during render (not in
  // an effect) so columnMode is settled before the feed effect runs — avoids a double feed restart.
  // Editing the same source in place keeps the user's current toggle.
  if (source && source.id !== modeSourceId) {
    setModeSourceId(source.id);
    setColumnMode(source.columnMode);
  }

  // Remount the grid on every feed (re)start so AG Grid init-only options (getRowId, the auto-gen
  // column strategy) are re-applied. Keyed by source + column mode + an explicit reconnect/edit nonce.
  const gridKey = `${source?.id ?? 'none'}:${columnMode}:${reconnectNonce}`;

  const switchSource = (src: BlotterSource) => navigate(`/blotter?source=${encodeURIComponent(src.id)}`);
  const openNew = () => {
    setEditSource(null);
    setDialogOpen(true);
  };
  const openEdit = (src: BlotterSource) => {
    setEditSource(src);
    setDialogOpen(true);
  };

  const getRowId = useCallback(
    (p: GetRowIdParams) => {
      const data = p.data as Row;
      if (source?.mode === 'append') return String(data['__id']);
      return String(data[source?.keyField ?? '__id']);
    },
    [source],
  );

  const gridOptions = useMemo<GridOptions>(
    () =>
      columnMode === 'auto-gen'
        ? {
            autoGenerateColumnDefs: { objectValues: 'flatten', nullishValues: 'include' },
            processAutoGeneratedColumnDefs: applyInferredFormats(formats),
          }
        : {},
    [columnMode, formats],
  );

  // Create + start the feed when the source / column mode / remount key changes.
  useEffect(() => {
    const grid = gridRef.current;
    if (!source || !grid) return;
    setColumns([]);
    setRowData([]);
    setFeedState(IDLE);

    const ops: GridOps = {
      addRows: (rows) => grid.addRows$.next(rows),
      updateRows: (rows) => grid.updateRows$.next(rows),
      deleteRows: (rows) => grid.deleteRows$.next(rows),
      // The React grid has no setInitialRowData — seed via the rowData prop state.
      setInitialRowData: (rows) => setRowData(rows),
    };
    const feed = new BlotterFeed(source, ops, (rec) => {
      const inferred = inferColumns(rec, source.keyField);
      setFormats(inferred.formats);
      if (columnMode !== 'auto-gen') setColumns(inferred.columns);
    });
    feedRef.current = feed;
    const off = feed.subscribe(() => setFeedState(feed.getState()));
    setFeedState(feed.getState());
    void feed.start();

    return () => {
      off();
      void feed.stop();
      feedRef.current = null;
    };
  }, [source, columnMode, reconnectNonce]);

  const reconnect = () => setReconnectNonce((n) => n + 1);
  const disconnect = () => void feedRef.current?.stop();
  const switchMode = (mode: ColumnMode) => {
    if (mode === columnMode) return;
    setColumnMode(mode); // gridKey includes columnMode, so this remounts with the new strategy
  };

  const sourceDialog = (
    <AdHocSourceDialog
      open={dialogOpen}
      source={editSource}
      onOpenChange={setDialogOpen}
      onSaved={(src) => {
        setDialogOpen(false);
        setReconnectNonce((n) => n + 1); // remount even when editing the active source in place
        switchSource(src);
      }}
    />
  );

  if (!source) {
    return (
      <div className="flex flex-col items-center gap-3 pt-16 text-center">
        <Database className="size-9 opacity-40" />
        <p className="font-semibold text-lg m-0">No data source selected</p>
        <p className="opacity-70 m-0">Pick a configured source — or define your own — to start the blotter.</p>
        <div className="flex gap-2 mt-4">
          <SourcePicker
            activeId={null}
            onSelect={switchSource}
            onNew={openNew}
            onEdit={openEdit}
            trigger={
              <Button>
                Select data source <ChevronDown className="size-4" />
              </Button>
            }
          />
          <Button variant="outline" onClick={openNew}>
            <Plus className="size-4" /> New data source
          </Button>
        </div>
        {sourceDialog}
      </div>
    );
  }

  const statusVariant =
    feedState.status === 'live'
      ? 'success'
      : feedState.status === 'error'
        ? 'destructive'
        : feedState.status === 'connecting' || feedState.status === 'snapshot-loading'
          ? 'warning'
          : 'secondary';

  return (
    <div className="flex flex-col h-full gap-3">
      <div className="flex items-center gap-3 flex-wrap">
        <SourcePicker
          activeId={source.id}
          onSelect={switchSource}
          onNew={openNew}
          onEdit={openEdit}
          trigger={
            <button
              type="button"
              aria-label="Change data source"
              className="flex items-center gap-2 -ml-2 rounded-md border border-transparent px-2 py-1 hover:bg-accent hover:border-border"
            >
              <span className="font-bold text-lg">{source.name}</span>
              <Badge variant="secondary">{TRANSPORT_LABELS[source.transport]}</Badge>
              <Badge variant={modeVariant(source.mode)}>{MODE_LABELS[source.mode]}</Badge>
              <ChevronDown className="size-3.5 opacity-60" />
            </button>
          }
        />

        <div className="flex items-center gap-3">
          <Badge variant={statusVariant}>{feedState.status}</Badge>
          <span className="text-sm opacity-70">{feedState.rowCount} rows</span>
          <span className="text-sm opacity-70">{feedState.msgsPerSec} msg/s</span>
        </div>

        <div className="ml-auto flex items-center gap-2 flex-wrap">
          <div className="inline-flex rounded-md border overflow-hidden">
            {(['infer', 'auto-gen'] as ColumnMode[]).map((m) => (
              <button
                key={m}
                onClick={() => switchMode(m)}
                className={`text-sm px-3 py-1.5 ${columnMode === m ? 'bg-primary text-primary-foreground' : 'bg-background'}`}
              >
                {m === 'infer' ? 'Infer' : 'Auto (v36)'}
              </button>
            ))}
          </div>
          <Button variant="ghost" size="sm" onClick={reconnect}>
            <RefreshCw className="size-4" /> Reconnect
          </Button>
          <Button variant="ghost" size="sm" onClick={disconnect}>
            <Square className="size-4" /> Disconnect
          </Button>
        </div>
      </div>

      {feedState.error && (
        <div className="rounded-md border border-destructive bg-destructive/10 text-destructive px-3 py-2 text-sm">
          {feedState.error}
        </div>
      )}

      <div className="flex-1 min-h-0">
        <MacroReactGrid
          key={gridKey}
          ref={gridRef}
          columns={columns}
          rowData={rowData}
          columnFormats={columnMode === 'infer' ? formats : {}}
          gridOptions={gridOptions}
          getRowId={getRowId}
        />
      </div>

      {sourceDialog}
    </div>
  );
}
